[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0xb5e4425a4f484e6744cf333a719a02d49fb9040e48905d8d036ca2ebcfd7d9de'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]